# Generated by Django 3.1.2 on 2024-07-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pedido_comprobante_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='comprobante_transferencia',
            field=models.ImageField(blank=True, null=True, upload_to='core/img/comprobante/'),
        ),
    ]
