# Generated by Django 3.1.2 on 2024-07-13 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
